version: '3.7'
services:
  app:
    container_name: vue-sample
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/usr/src/app'
    stdin_open: true
    tty: true
    command: npm run serve
